# Altera o nome da aplicação (opcional)
spring.application.name=agenda-contatos

# Habilita o Console Web do H2 para podermos ver o banco no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configura a URL de conexão do banco em memória
spring.datasource.url=jdbc:h2:mem:agendadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Mostra no console do IntelliJ os comandos SQL que o Spring/Hibernate está gerando
spring.jpa.show-sql=true
spring.jpa.properties.spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true